version: '3.8'

services:
  # --- 1. Database Service ---
  db:
    build: 
      context: ./server/postgres # Path to the Dockerfile in Step 1
      dockerfile: Dockerfile
    container_name: learning-path-db
    environment:
      POSTGRES_DB: learningpath_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ramya # Use a strong local password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # Map host port 5434 to container port 5432
    restart: unless-stopped

  # --- 2. Backend Service (Node/Express) ---
  server:
    build:
      context: ./server # Path to the Dockerfile in Step 2
      dockerfile: Dockerfile
    container_name: learning-path-server
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      PORT: 5000
      # Connect to the 'db' service using its internal Docker name and port
      DATABASE_URL: postgresql://postgres:ramya@db:5432/learningpath_db
      JWT_SECRET: your_local_jwt_secret_change_me_123 # Use your actual secret
    depends_on:
      - db
    restart: unless-stopped

  # --- 3. Frontend Service (React/Nginx) ---
  client:
    build:
      context: ./client # Path to the Dockerfile in Step 3
      dockerfile: Dockerfile
    container_name: learning-path-client
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    depends_on:
      - server # Wait for the backend API to be ready
    restart: unless-stopped

volumes:
  postgres_data: